[package]
name = "rush-core"
version = "0.1.0"
edition = "2021"
authors = ["focus172 <evan.stokdyk@gmail.com>"]

[dependencies]
# os_pipe = "1.1"
# duct = "0.13"
# nix = { version = "0.28", features = ["fs", "user"] }
libc = "0.2"
resu = { package = "error-stack", version = "0.4" }
log = "0.4"
