[package]
name = "rush-shard"
version = "0.1.0"
authors = ["focus172 <evan.stokdyk@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rush-core = { path = "../rush-core/" }
resu.workspace = true
libshards.workspace = true
